# Generated by Django 5.0.4 on 2024-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlzheimerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alzheimer')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
