# Generated by Django 5.0.4 on 2024-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0004_alzheimerimages_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTumorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brain_tumor')),
            ],
        ),
    ]
