# Generated by Django 5.0.4 on 2024-04-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0005_braintumorimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alzheimer')),
            ],
        ),
    ]
