# Generated by Django 5.0.4 on 2024-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0006_tbimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbimages',
            name='image',
            field=models.ImageField(upload_to='tb'),
        ),
    ]
